export interface DefaultCategory {
  name: string;
  type: 'default' | 'savings' | 'transfer' | 'fallback';
}

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  { name: 'Lebensmittel', type: 'default' },
  { name: 'Restaurant & Lieferdienst', type: 'default' },
  { name: 'Drogerie & Körperpflege', type: 'default' },
  { name: 'Haushalt', type: 'default' },
  { name: 'Kleidung & Schuhe', type: 'default' },
  { name: 'Online Shopping', type: 'default' },
  { name: 'Elektronik & Technik', type: 'default' },
  { name: 'Wohnen & Miete', type: 'default' },
  { name: 'Energie & Nebenkosten', type: 'default' },
  { name: 'Telefon & Internet', type: 'default' },
  { name: 'Versicherungen', type: 'default' },
  { name: 'Kredit & Darlehen', type: 'default' },
  { name: 'Bankgebühren', type: 'default' },
  { name: 'Steuern & Abgaben', type: 'default' },
  { name: 'Gesundheit & Apotheke', type: 'default' },
  { name: 'Kraftstoff & Tanken', type: 'default' },
  { name: 'Auto & Werkstatt', type: 'default' },
  { name: 'ÖPNV & Nahverkehr', type: 'default' },
  { name: 'Reisen & Urlaub', type: 'default' },
  { name: 'Freizeit & Unterhaltung', type: 'default' },
  { name: 'Sport & Fitness', type: 'default' },
  { name: 'Abonnements & Streaming', type: 'default' },
  { name: 'Bildung & Bücher', type: 'default' },
  { name: 'Kinder & Familie', type: 'default' },
  { name: 'Haustier', type: 'default' },
  { name: 'Geschenke & Spenden', type: 'default' },
  { name: 'Garten & Haus', type: 'default' },
  { name: 'Kinderbetreuung', type: 'default' },
  { name: 'Gehalt & Lohn', type: 'default' },
  { name: 'Mieteinnahmen', type: 'default' },
  { name: 'Nebeneinkünfte', type: 'default' },
  { name: 'Einspeisung Photovoltaik', type: 'default' },
  { name: 'Sparen & Anlage', type: 'savings' },
  { name: 'Bargeldabhebung', type: 'default' },
  { name: 'Umbuchung & Übertrag', type: 'transfer' },
  { name: 'Sonstiges', type: 'fallback' },
];

export const DEFAULT_RULES = [
  { pattern: 'REWE|LIDL|ALDI|NETTO|KAUFLAND|EDEKA|PENNY|NORMA', category: 'Lebensmittel' },
  { pattern: 'MH MULLER|MUELLER|ROSSMANN|DM-DROGERIE|DM FIL', category: 'Drogerie & Körperpflege' },
  { pattern: 'FRESSNAPF|Tierhandlung|ZOOPLUS|Futterhaus', category: 'Haustier' },
  { pattern: 'VPV|VERSICHERUNG|ALLIANZ|HUK|ARAG|AXA|ERGO', category: 'Versicherungen' },
  { pattern: 'LECHWERKE|LEW Verteilnetz|energie schwaben|GAS Abschlag|Stadtwerke|Abfallentsorgung|Müllabfuhr|Abfallwirtschaft|Wertstoffhof|Wasserkosten|Abwasser|Zweckverband|Stadtentwässerung|Wasserversorgung|Wasserzweck', category: 'Energie & Nebenkosten' },
  { pattern: 'PHOTOVOLTAIK|Einspeisung', category: 'Einspeisung Photovoltaik' },
  { pattern: 'TELEKOM|VODAFONE|O2 |INTERNET|1&1', category: 'Telefon & Internet' },
  { pattern: 'APOTHEKE|ARZT|KRANKENHAUS|KLINIK|ZAHNARZT|OPTIKER', category: 'Gesundheit & Apotheke' },
  { pattern: 'Grundsteuer|Gemeinde Buttenwiesen|Finanzamt|GEZ|Rundfunk', category: 'Steuern & Abgaben' },
  { pattern: 'Teilzahlung Darlehen|Darlehen', category: 'Kredit & Darlehen' },
  { pattern: 'Haushaltsgeld|Haushaltskonto', category: 'Haushalt' },
  { pattern: 'AMAZON|EBAY|ZALANDO|OTTO|TEMU|SHEIN', category: 'Online Shopping' },
  { pattern: 'TANKSTELLE|ARAL|SHELL|BP|ESSO|JET |TOTAL', category: 'Kraftstoff & Tanken' },
  { pattern: 'BAHN|DB Vertrieb|FLIXBUS|MVV|ÖPNV|Nahverkehr', category: 'ÖPNV & Nahverkehr' },
  { pattern: 'FLUG|LUFTHANSA|TAXI|UBER|BOOKING|AIRBNB|Hotel', category: 'Reisen & Urlaub' },
  { pattern: 'Kontoführung|Abschluss', category: 'Bankgebühren' },
  { pattern: 'Aufrundkonto|Aufrundung|Sparrate|Sparen\\s|Depot|ETF', category: 'Sparen & Anlage' },
  { pattern: 'LIEFERANDO|PIZZA|MCDONALDS|BURGER KING|SUBWAY|STARBUCKS|RESTAURANT|IMBISS', category: 'Restaurant & Lieferdienst' },
  { pattern: 'SPOTIFY|NETFLIX|DISNEY|APPLE\\.COM|GOOGLE \\*|DAZN|YOUTUBE', category: 'Abonnements & Streaming' },
  { pattern: 'PAYPAL', category: 'Online Shopping' },
  { pattern: 'Miete|Kaltmiete|Warmmiete|Mietvertrag', category: 'Wohnen & Miete' },
  { pattern: 'GEHALT|LOHN|Bezüge|Entgelt', category: 'Gehalt & Lohn' },
  { pattern: 'Geldautomat|Abhebung|ATM', category: 'Bargeldabhebung' },
  { pattern: 'Umbuchung|Übertrag|Eigenübertrag|Kontoübertrag|Sparübertrag|eigenes Konto', category: 'Umbuchung & Übertrag' },
  { pattern: 'TÜV|ADAC|Werkstatt|KFZ|Reparatur Auto', category: 'Auto & Werkstatt' },
  { pattern: 'FITNESSSTUDIO|GYM|MCFIT|FITX|Sportverein', category: 'Sport & Fitness' },
  { pattern: 'KINO|THEATER|KONZERT|EVENTIM|TICKETMASTER', category: 'Freizeit & Unterhaltung' },
  { pattern: 'H&M|ZARA|C&A|PRIMARK|DEICHMANN|SCHUH', category: 'Kleidung & Schuhe' },
  { pattern: 'Mietzahlung|Mieteingang|Mieter|Mietüberweisung', category: 'Mieteinnahmen' },
  { pattern: 'Rückerstattung|Erstattung|Gutschrift|Rückvergütung', category: 'Nebeneinkünfte' },
  { pattern: 'OBI|HORNBACH|BAUHAUS|TOOM|BAYWA|Gartencenter|DEHNER|Baumarkt|HAGEBAU', category: 'Garten & Haus' },
  { pattern: 'KITA|Kindergarten|Kinderbetreuung|Kindertagesstätte|Tagesmutter|Hort|Krippe', category: 'Kinderbetreuung' },
];
